### ISSUE TITLE
Add to melpa

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-rustic/rustic#1]
Before this repo can be added to melpa, we need to demonstrate that this is *the* canonical fork that should be used. Given that, I think we should spread the word and get other people using this fork before we open a PR to change the repo on Melpa.

**Comment by psibi** [comment]
> Given that, I think we should spread the word and get other people using this fork before we open a PR to change the repo on Melpa.

Let me see if I can get my blog post soon.

**Comment by psibi** [comment]
I have written an initial post here: https://psibi.in/posts/rustic.html

Let me know what you think, Feel free to send PR's here if you think more context/information or edits will help: https://github.com/psibi/psibi.github.io/blob/main/posts/rustic.md

**Comment by CeleritasCelery** [comment]
This is a good explanation of the situation. I would explicitly call out the new repo URL in the post.

**Comment by psibi** [comment]
@CeleritasCelery How about this: https://github.com/psibi/psibi.github.io/pull/2 ?

**Comment by CeleritasCelery** [comment]
LGTM

**Comment by phillord** [comment]
Thanks for taking this forward. I was getting a bit worried about rustic when I saw it was getting behind.

**Comment by psibi** [comment]
Closing this since this has been added to MELPA.
