### ISSUE TITLE
replace external dependecy `xterm-color` with Emacs core (built-in) `ansi-color`

### ISSUE THREAD

**Issue by ed9w2in6** [emacs-rustic/rustic#16]
originally at: https://github.com/brotzeit/rustic/issues/558

Hi I see that this fork is maintained to I copied my issue here.

--------

Hmm I had took a look lately with `ripgrep` and it seems that this package only uses `xterm-color` for `xterm-color-filter`, correct me if I am wrong.

If I am right about this, I believe they can be replaced with the builtin `ansi-color-apply`.

This can reduce external dependencies and make configuration simpler.
related: https://github.com/brotzeit/rustic/issues/401

**Comment by ed9w2in6** [comment]
Please note that `ansi-color` does NOT deal with non-color ANSI escape codes.

So some logic are need to deal with them, such as by [filtering them out with regex](https://emacs.stackexchange.com/questions/24698/ansi-escape-sequences-in-compilation-mode)

**Comment by ed9w2in6** [comment]
The default values provided by `rustic` is also quite ugly IMO, in which the default ones at `xterm-color` are better:

Perhaps a partial fix is to just remove `rustic-ansi-faces` and rely on configuration at `xterm-color`, I cannot see why `rustic` needs a custom color scheme.

The name is also misleading - `rustic-ansi-faces` does NOT contain any faces, they are just colours.

**Comment by CeleritasCelery** [comment]
I think we should stick with `xterm-color` because it is more comprehensive than `ansi-color`. However I am fine with changing the colors to the defaults. That way it will follow the users theme. If you want to open a PR we can merge that.
