### ISSUE TITLE
Do not provide the test-helper feature

### ISSUE THREAD

**Issue by tarsius** [emacs-rustic/rustic#18]
`test-helper.el` isn't a library intended to be loaded with `require`. Instead it is loaded with `load` by `ert-runner` itself and that does not use `require` to do so.

Because of that, it is confusing to `provide` a feature.  It also wouldn't be possible to use `require` to reliably load `test-helper` because that might, depending on the order of `load-path`, load the `test-helper.el` of another package.

There aren't many packages left that have that defect but that's only because I got them to fix this issue. It would be great if you could fix it in your package as well.

This is also discussed at rejeep/ert-runner.el#38.

**Comment by tarsius** [comment]
Thanks!

**Comment by tarsius** [comment]
Uh, unfortunately it looks like you'll have to use `load` with a relative file name.

**Comment by tarsius** [comment]
I've I remember correctly, the safest way looks something like:

```elisp
(load (expand-file-name "test-helper.el"
                        (file-name-directory
                         (or load-file-name buffer-file-name))))
```

**Comment by CeleritasCelery** [comment]
Thanks. I fat finger they keys and push it to the main branch instead of a PR branch I could run CI against.

**Comment by tarsius** [comment]
Thanks again!
