### ISSUE TITLE
Enable Rust-Analyzer diagnostics

### ISSUE THREAD

**Issue by rakanalh** [emacs-rustic/rustic#20]
Recently i started checking out Neovim's distributions to see how Rust development there would be.
One of the things i found was the fact that rust-analyzer provides diagnostics to the code that rustic does not display:

Neovim:
![image](https://github.com/emacs-rustic/rustic/assets/195829/0acffea8-b4c3-48ee-a672-103d75cb4b6c)

Emacs (Doom):
![image](https://github.com/emacs-rustic/rustic/assets/195829/9dbc022f-8ea0-4738-8e5f-f9ceef936ad4)

Though the following are lsp-mode configuration, i believe this could be set & configured by Rustic.
```elisp
   lsp-rust-analyzer-diagnostics-enable t
   lsp-rust-analyzer-cargo-watch-command "clippy"
   lsp-rust-analyzer-cargo-override-command ["cargo", "clippy", "--message=format=json"]
   lsp-rust-analyzer-cargo-extra-env ["SKIP_GUEST_BUILD=1"]
   lsp-diagnostic-clean-after-change t
```

Is this part of rustic already or would be something that needs to be implemented?

**Comment by CeleritasCelery** [comment]
I don't use doom, so I am not sure how it configures things. But I don't understand how the settings you specify give the behavior you want. 

1. `lsp-rust-analyzer-diagnostics-enable` is default, so we don't need to set that.
2. both the inline warnings you point to are part of `cargo check` not `cargo clippy`, so I don't understand why changing the watch command makes a difference.
3. what is setting `lsp-rust-analyzer-cargo-override-command` actually doing?
4. what does `SKIP_GUEST_BUILD` do?
5. "clean after change" is general lsp setting, and not something that is specific to rust-analyzer.

FWIW, I see the inline diagnostics like you want in my lsp setup. I think it is part of [lsp-ui](https://github.com/emacs-lsp/lsp-ui)

**Comment by rakanalh** [comment]
> I don't use doom, so I am not sure how it configures things. But I don't understand how the settings you specify give the behavior you want.
> 
>     1. `lsp-rust-analyzer-diagnostics-enable` is default, so we don't need to set that.
> 
>     2. both the inline warnings you point to are part of `cargo check` not `cargo clippy`, so I don't understand why changing the watch command makes a difference.
> 
>     3. what is setting `lsp-rust-analyzer-cargo-override-command` actually doing?
> 
>     4. what does `SKIP_GUEST_BUILD` do?
> 
>     5. "clean after change" is general lsp setting, and not something that is specific to rust-analyzer.
> 
> 
> FWIW, I see the inline diagnostics like you want in my lsp setup. I think it is part of [lsp-ui](https://github.com/emacs-lsp/lsp-ui)

![image](https://github.com/emacs-rustic/rustic/assets/195829/1006af31-5095-4977-aa28-2db2900efb49)

I have tested on a simpler code and removed the settings but still diagnostics as you can see.

> both the inline warnings you point to are part of cargo check not cargo clippy, so I don't understand why changing the watch command makes a difference.

Clippy is a bit more thorough which is why i wanted to set that. 

> what is setting lsp-rust-analyzer-cargo-override-command actually doing?
This is related to rust-analyzer's `checkOnSave` where you can override the command that is used to check a file when saved. The docs say:
> Advanced option, fully override the command rust-analyzer uses for checking.
> The command should include `--message=format=json` or similar option."

> what does SKIP_GUEST_BUILD do?

Probably irrelevant to this as this setting a project specific env var that i pasted here by mistake.

**Comment by CeleritasCelery** [comment]
This is what I see with that program
![Screenshot 2024-07-08 at 12 14 37 PM](https://github.com/emacs-rustic/rustic/assets/10623982/14e5ce76-e7f6-425d-b204-74d9901e8d0e)

This is part of `lsp-ui-sideline-mode`.

**Comment by rakanalh** [comment]
You're right... probably something wrong with my configs. 

Thanks
