### ISSUE TITLE
cargo clippy: Refresh doesn't preserve custom arguments passed

### ISSUE THREAD

**Issue by psibi** [emacs-rustic/rustic#22]
Pressing `g` in an already existing buffer doesn't seem to remember the arguments.

Note that this is not the case for:
- rustic-cargo-build
- rustic-cargo-test

**Comment by CeleritasCelery** [comment]
`rustic-cargo-build` and `rustic-cargo-test` have a specific function bound for doing recompile:

https://github.com/emacs-rustic/rustic/blob/efa6135f8426aa86b6a124ce81bc54959a1d6431/rustic-cargo.el#L142

We could add that for cargo clippy as well, but I would like to see a way to define this for all cargo commands.

**Comment by psibi** [comment]
Yeah, it would be ideal to have it for all commands. I think I have been historically adding to the one which I use more frequently. :-)
