### ISSUE TITLE
Format-on-save open the same file in popup

### ISSUE THREAD

**Issue by koptan** [emacs-rustic/rustic#33]
When I do save my buffer I am doing format-on save and I see the error message in rustic-complication mode window, which is good, but when I fix all the issues in my code and make it work and save it again, in rustic-complication mode window it's opening the same file that I am working on it, because there is no errors !!

any solution for this behavior?

Screenshots:
Here I can see the error in popup ... all good:
![image](https://github.com/user-attachments/assets/5b85f94f-cb43-4f45-b165-618f09e3828f)

Here in same popup after fixing all issues in my code, it's just opening the same file !!
![image](https://github.com/user-attachments/assets/5600950d-5f02-4342-8863-629670f0b1a9)

**Comment by psibi** [comment]
I believe you have enabled `rustic-format-on-save` ? I'm open to pull requests for fixing the issue.

**Comment by koptan** [comment]
@psibi yes `rustic-format-on-save` is enabled, sorry I still new to emacs world and lisp, so I don't think I will be able to provide any PR soon.

**Comment by CeleritasCelery** [comment]
So this is a windowing issue correct? Essentially you want it to remove the popup window instead of replacing it with a different buffer.

**Comment by koptan** [comment]
> So this is a windowing issue correct? Essentially you want it to remove the popup window instead of replacing it with a different buffer.

Yes correct, when rustfmt has no issue to display, we should close the window.
