### ISSUE TITLE
Cannot install on emacs 27.1

### ISSUE THREAD

**Issue by garro95** [emacs-rustic/rustic#37]
When trying to install on emacs 27.1 (shipped with ubuntu 22.04 LTS) the following error prevents the installation
```
Error (use-package): Failed to install rustic: Package ‘project-0.3.0’ is unavailable
```

**Comment by psibi** [comment]
Is it possible to test it in 27.2 (or latest preferably) ? We have CI running for 27.2 and I can confirm that it should be working there.

**Comment by psibi** [comment]
Closing this issue as there have been no recent updates or further information provided. I've also been unable to replicate the reported behavior on my end.
