### ISSUE TITLE
Cannot install version 20240819.1214 from Melpa

### ISSUE THREAD

**Issue by jman-schief** [emacs-rustic/rustic#39]
Hi,

I'm trying to install rustic from Melpa (`20240819.1214` at the time of writing), with `use-package`:
```lisp
(use-package rustic
  :ensure t
  :config
  (setq rustic-format-on-save nil)
  (setq rustic-lsp-client 'eglot)
  (add-hook 'eglot--managed-mode-hook (lambda () (flymake-mode -1)))
  :custom
  (rustic-cargo-use-last-stored-arguments t))
```

The installation fails with this error:
```
Error (use-package): Failed to install rustic: https://melpa.org/packages/rust-mode-20240520.749.tar: Not found
```

I am not too famiiar with how Melpa works, so I'm not sure where the issue is: on Melpa or the rustic recipe published from the package author? Why is the installation looking for an old version of rust-mode instead of the latest (`20240822.245` at the time of writing) which is instead available on Melpa?

Thanks for a suggestion on how to proceed.

**Comment by psibi** [comment]
That is surprising. What if you do something like this instead:

```
(use-package rust-mode
  :ensure t)

(use-package rustic
  :ensure t
  :after (rust-mode)
  :config
  (setq rustic-format-on-save nil)
  (setq rustic-lsp-client 'eglot)
  (add-hook 'eglot--managed-mode-hook (lambda () (flymake-mode -1)))
  :custom
  (rustic-cargo-use-last-stored-arguments t))
```

**Comment by psibi** [comment]
Also try running `M-x package-list-packages` as that might also update your MELPA index and possibly fix the issue without the above workaround.
