### ISSUE TITLE
Please consider bumping rust-mode dependency version and making a melpa-stable release

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-rustic/rustic#40]
The last rustic melpa-stable release was made two years ago, and the rust-mode dependency is for 1.0.3, which is even older.  Now that rust-mode has been recently released as 1.0.6 on melpa-stable (https://github.com/rust-lang/rust-mode/issues/551), please consider bumping the dependency and making a melpa-stable release for rustic.

Thank you,

**Comment by psibi** [comment]
> making a melpa-stable release for rustic.

Agree.

> Please consider bumping rust-mode dependency version

Is that required ? The Package-Version header line specifies the minimum version that is required for rustic to function. More details here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

**Comment by psibi** [comment]
Thanks! Bumping seemed easier than documenting it. :-)
