### ISSUE TITLE
Change the org icon?

### ISSUE THREAD

**Issue by jcs090218** [emacs-rustic/rustic#53]
I recommend changing the organization's image to something else so it's easier to differentiate it from other organizations. 🤔

I've created this simple logo (Emacs + Rust). WDYT?

![emacs-rustic](https://github.com/user-attachments/assets/d6aff2c1-fff7-4aa0-9a46-135a4d8076d1)

**Comment by jcs090218** [comment]
Nice! Thanks! :D

**Comment by psibi** [comment]
How did you make the icon by the way ? :-)

**Comment by jcs090218** [comment]
> How did you make the icon by the way ? :-)

Photoshop. 😜
