### ISSUE TITLE
rustic-compile always prompts interactively (even when called from elisp)

### ISSUE THREAD

**Issue by holgerschurig** [emacs-rustic/rustic#57]
### Experience behavior

The compile method of Rustic differs to the built-in one: it is always interactively prompting for a compile-command, no matter if it's called interactively or programmatically.

Example 1:

```lisp=
(rustic-compile "cargo build")
```

Here I provided my own compile command, and I expect the compilation to start immediately. But it doesn't, I'm getting needlessly asked for a compile-command. This makes (rustic-compile ...) unusable for scripting in Elisp.

Example 2:

```lisp=
(let ((compilation-read-command nil))
 (rustic-compile "cargo build"))
```

Even that generates a prompt for the interactive command.

### Expected Behavior

Contrast this with

```lisp=
(compile "cargo build")
```

which doesn't prompt at all and just does what it is called to do: compile my source. That is: the provided optional argument overrides the variable compile-command, and makes it not prompt. The "not prompting" btw also happens when compilation-read-command is t.

### Version of rustic-mode

This is on rustic-mode HEAD d765680373234a6c231acf20c76b07422afcfdf9

**Comment by psibi** [comment]
What if you use the function `rustic-cargo-build` instead ?

**Comment by holgerschurig** [comment]
So, apart from that snarky (but true!) remark they are not equivalent. "rustic-compile" searches uses some nice logic to change into the proper directory, which might not be project-root. And maybe I don't want to run "cargo build" there, but e.g. "make distribution.tar" ... but from the proper directory and not from the current source directory.

rustic-cargo-build doesn't have this directory changing logic.

It also only is able to call cargo. And while cargo is (relatively) good to do things to get to an executable, it is very bad at doing things with such an executable (e.g. signing, tarring, uploading etc etc). So no, the function you suggested isn't really a substitute.

So I still suggest to make rustic-compile behave like ideomatic emacs lisp code: prompt ONLY if not explicitly given an argument.

**Comment by psibi** [comment]
Ah, I see what you mean. I'm happy to accept PR's for the same. :-)

**Comment by CeleritasCelery** [comment]
I also noticed that the old code would have failed in this code path, if we ever hit it. It was also passing in the command as an argument.


https://github.com/emacs-rustic/rustic/blob/main/rustic-popup.el#L152
