### ISSUE TITLE
automatic imports stopped working

### ISSUE THREAD

**Issue by the-drunk-coder** [emacs-rustic/rustic#61]
Hi,

I've been using rustic mode for a while now, but today I noticed that automated imports stopped working.

That is, when starting to type a type name, the options show up, but if I hit "return" or "tab", nothing happens, when in the past the required type would be added automatically.

Not sure whether that's a rustic issue, but maybe someone can point me in the right direction?

Best,
N

**Comment by the-drunk-coder** [comment]
rust-analyzer

**Comment by the-drunk-coder** [comment]
btw, not sure whether that helps but I observed some other problems as well that make the overall experience way less smooth that it was just a couple of weeks ago ... summarized them here: 

https://users.rust-lang.org/t/recent-problems-with-emacs-rustic

**Comment by Erk-** [comment]
Could you try to log the communication between `lsp-mode` and `rust-analyzer` as described here? https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/#log-client-server-json

Then it should be possible to figure out if it happens because of `lsp-mode` or something else.

**Comment by the-drunk-coder** [comment]
@Erk- what would I be looking out for ?

**Comment by psibi** [comment]
One of the techniques which I use to debug this kind of issue is follow this:

- Try editing the same Rust project using Vscode using the same version of Rust-analyzer
- See if you are able able to reprduce it. If you are able to reproduce it, this is likely a rust-analyzer issue.
- If you are not able to reproduce it, get the logs based on the above link which @Erk-  put.
- Get also the logs for VSCode and compare them to see why they differ.

**Comment by Erk-** [comment]
The request/response which inserts the imports is `completionItem/resolve` which is the one you want to look for.

**Comment by the-drunk-coder** [comment]
@Erk- 

the items look like this: 

```
[Trace - 03:28:31 PM] Sending request 'completionItem/resolve - (168)'.
Params: {
  "label": "HashMap (use std::collections::HashMap)",
  "kind": 22,
  "deprecated": null,
  "sortText": "80000000",
  "filterText": "HashMap",
  "textEdit": {
    "newText": "HashMap",
    "insert": {
      "start": {
        "line": 6,
        "character": 15
      },
      "end": {
        "line": 6,
        "character": 19
      }
    },
    "replace": {
      "start": {
        "line": 6,
        "character": 15
      },
      "end": {
        "line": 6,
        "character": 19
      }
    }
  },
  "additionalTextEdits": [],
  "data": {
    "position": {
      "textDocument": {
        "uri": "file:///[...].rs"
      },
      "position": {
        "line": 6,
        "character": 19
      }
    },
    "imports": [
      {
        "full_import_path": "std::collections::HashMap",
        "imported_name": "HashMap"
      }
    ],
    "version": 34,
    "trigger_character": null
  }
}
```

**Comment by Erk-** [comment]
@the-drunk-coder Does `rust-analyzer` not send a response back?

**Comment by CeleritasCelery** [comment]
Also, make sure that `lsp-rust-analyzer-completion-auto-import-enable` and `lsp-completion-enable-additional-text-edit` are both `t`.

**Comment by the-drunk-coder** [comment]
> Also, make sure that `lsp-rust-analyzer-completion-auto-import-enable` and `lsp-completion-enable-additional-text-edit` are both `t`.

Added them to my `.emacs` but that doesn't change anything ...

**Comment by the-drunk-coder** [comment]
> @the-drunk-coder Does `rust-analyzer` not send a response back?

yes, they look like this:

```
[Trace - 04:44:35 PM] Received response 'completionItem/resolve - (162)' in 289ms.
Result: {
  "label": "HashSet (use std::collections::HashSet)",
  "kind": 22,
  "sortText": "80000000",
  "filterText": "HashSet",
  "textEdit": {
    "newText": "HashSet",
    "insert": {
      "start": {
        "line": 48,
        "character": 10
      },
      "end": {
        "line": 48,
        "character": 15
      }
    },
    "replace": {
      "start": {
        "line": 48,
        "character": 10
      },
      "end": {
        "line": 48,
        "character": 15
      }
    }
  },
  "additionalTextEdits": []
}
```

**Comment by psibi** [comment]
Looks like an upstream issue: https://github.com/rust-lang/rust-analyzer/issues/18363

**Comment by the-drunk-coder** [comment]
can confirm, it works again :)
